### PR TITLE
Combination?

### PR DESCRIPTION
**Pull request by Jonatan-r**
Hi, I am all new to GitHub, and I would like to know if it's at all possible to combine the features of these two branches (I believe they're called?)?. The ones added by hellogerard and the ones added by cjanis.
Please help! :D

Best to you, whomever will read this.
Jonatan.

### CODE REVIEW

**Comment by hellogerard** [comment]
Hi, there's no great way to do this, so I just did it manually for you. To explain, I just merged that `cjanis:master` branch on top of my `sequential` branch. I just pushed the new branch to [`pr-1`](https://github.com/hellogerard/jquery.typer.js/tree/pr-1). It's untested, so try it out first. Hope this helps!

**Comment by Jonatan-r** [comment]
Seems to work very well!! Thank you VERY much!! :D You're the best!! Thanks again. For your work :)

**Comment by Jonatan-r** [comment]
All the very best to you from here,
Jonatan. :)

**Comment by Jonatan-r** [comment]
:D

**Pull request closed without merging**
